email = "popu-servers+jenkins@populate.tools "
pipeline {
    agent any
    environment {
        PATH = "$HOME/.rbenv/shims:$PATH"
        GOBIERTO_ETL_UTILS = "/var/www/gobierto-etl-utils/current"
        SANTFELIU_ETL = "/var/www/gobierto-etl-sant-feliu/current"
        STORAGE_DIR = "/tmp/sant-feliu"
        // Variables that must be defined via Jenkins UI:
        // GOBIERTO = "/var/www/gobierto/current"
        // SANT_FELIU_API_TOKEN
    }
    options {
        retry(3)
    }
    stages {
        stage('Extract > Download data sources') {
            steps {
              sh '''#!/bin/bash
                source ${SANTFELIU_ETL}/.rbenv-vars;
                cd ${GOBIERTO_ETL_UTILS};
                ruby operations/download/run.rb 'https://www.santfeliu.cat/scripts/previsio_pressupost?execute&any=20&key='$SANT_FELIU_API_TOKEN ${STORAGE_DIR}/budgets-planned-2020.json --compatible;
                ruby operations/download/run.rb 'https://www.santfeliu.cat/scripts/pressupost_despesa?execute&any=20'  ${STORAGE_DIR}/budgets-executed-expense-2020.json --compatible;
                ruby operations/download/run.rb 'https://www.santfeliu.cat/scripts/pressupost_ingres?execute&any=20'   ${STORAGE_DIR}/budgets-executed-income-2020.json --compatible;
                ruby operations/download/run.rb 'https://www.santfeliu.cat/scripts/previsio_pressupost?execute&any=21&key='$SANT_FELIU_API_TOKEN ${STORAGE_DIR}/budgets-planned-2021.json --compatible;
                ruby operations/download/run.rb 'https://www.santfeliu.cat/scripts/pressupost_despesa?execute&any=21'  ${STORAGE_DIR}/budgets-executed-expense-2021.json --compatible;
                ruby operations/download/run.rb 'https://www.santfeliu.cat/scripts/pressupost_ingres?execute&any=21'   ${STORAGE_DIR}/budgets-executed-income-2021.json --compatible;
              '''
            }
        }
        stage('Extract > Check valid JSON') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-json/run.rb ${STORAGE_DIR}/budgets-planned-2020.json"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-json/run.rb ${STORAGE_DIR}/budgets-executed-expense-2020.json"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-json/run.rb ${STORAGE_DIR}/budgets-executed-income-2020.json"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-json/run.rb ${STORAGE_DIR}/budgets-planned-2021.json"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-json/run.rb ${STORAGE_DIR}/budgets-executed-expense-2021.json"
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-json/run.rb ${STORAGE_DIR}/budgets-executed-income-2021.json"

            }
        }
        stage('Extract > Check data source columns') {
            steps {
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/check-json-columns/run.rb ${STORAGE_DIR}/budgets-planned-2020.json"
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/check-json-columns/run.rb ${STORAGE_DIR}/budgets-executed-expense-2020.json"
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/check-json-columns/run.rb ${STORAGE_DIR}/budgets-executed-income-2020.json"
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/check-json-columns/run.rb ${STORAGE_DIR}/budgets-planned-2021.json"
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/check-json-columns/run.rb ${STORAGE_DIR}/budgets-executed-expense-2021.json"
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/check-json-columns/run.rb ${STORAGE_DIR}/budgets-executed-income-2021.json"
            }
        }
        stage('Transform > Transform planned budgets data files') {
            steps {
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/transform-planned/run.rb ${STORAGE_DIR}/budgets-planned-2020.json ${STORAGE_DIR}/budgets-planned-2020-transformed.json 2020"
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/transform-planned/run.rb ${STORAGE_DIR}/budgets-planned-2021.json ${STORAGE_DIR}/budgets-planned-2021-transformed.json 2021"
            }
        }
        stage('Transform > Transform executed budgets data files') {
            steps {
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/transform-executed/run.rb ${STORAGE_DIR}/budgets-executed-expense-2020.json ${STORAGE_DIR}/budgets-executed-expense-2020-transformed.json 2020 G"
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/transform-executed/run.rb ${STORAGE_DIR}/budgets-executed-income-2020.json  ${STORAGE_DIR}/budgets-executed-income-2020-transformed.json 2020 I"
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/transform-executed/run.rb ${STORAGE_DIR}/budgets-executed-expense-2021.json ${STORAGE_DIR}/budgets-executed-expense-2021-transformed.json 2021 G"
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/transform-executed/run.rb ${STORAGE_DIR}/budgets-executed-income-2021.json  ${STORAGE_DIR}/budgets-executed-income-2021-transformed.json 2021 I"
            }
        }
        stage('Load > Import planned budgets') {
            steps {
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/import-planned-budgets/run.rb ${STORAGE_DIR}/budgets-planned-2020-transformed.json 2020"
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/import-planned-budgets/run.rb ${STORAGE_DIR}/budgets-planned-2021-transformed.json 2021"
            }
        }
        stage('Load > Import executed budgets') {
            steps {
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/import-executed-budgets/run.rb ${STORAGE_DIR}/budgets-executed-expense-2020-transformed.json 2020"
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/import-executed-budgets/run.rb ${STORAGE_DIR}/budgets-executed-income-2020-transformed.json 2020"
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/import-executed-budgets/run.rb ${STORAGE_DIR}/budgets-executed-expense-2021-transformed.json 2021"
                sh "cd ${SANTFELIU_ETL}; ruby operations/gobierto_budgets/import-executed-budgets/run.rb ${STORAGE_DIR}/budgets-executed-income-2021-transformed.json 2021"
            }
        }
        stage('Load > Calculate totals') {
            steps {
              sh "echo '8211' > ${STORAGE_DIR}/organization.id.txt"
              sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/update_total_budget/run.rb '2020 2021' ${STORAGE_DIR}/organization.id.txt"
            }
        }
        stage('Load > Calculate bubbles') {
            steps {
              sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/bubbles/run.rb ${STORAGE_DIR}/organization.id.txt"
            }
        }
        stage('Load > Calculate annual data') {
            steps {
              sh "cd ${GOBIERTO}; bin/rails runner ${GOBIERTO_ETL_UTILS}/operations/gobierto_budgets/annual_data/run.rb '2020 2021' ${STORAGE_DIR}/organization.id.txt"
            }
        }
        stage('Load > Publish activity') {
            steps {
              sh "cd ${GOBIERTO}; bin/rails runner ${GOBIERTO_ETL_UTILS}/operations/gobierto/publish-activity/run.rb budgets_updated ${STORAGE_DIR}/organization.id.txt"
            }
        }
        stage('Load > Reset cache') {
            steps {
              sh "cd ${GOBIERTO}; bin/rails runner ${GOBIERTO_ETL_UTILS}/operations/gobierto/clear-cache/run.rb"
            }
        }
    }
    post {
        failure {
            echo 'This will run only if failed'
            mail body: "Project: ${env.JOB_NAME} - Build Number: ${env.BUILD_NUMBER} - URL de build: ${env.BUILD_URL}",
                charset: 'UTF-8',
                subject: "ERROR CI: Project name -> ${env.JOB_NAME}",
                to: email

        }
    }
}
